# Generated by Django 5.0.7 on 2024-08-03 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='stockQuantity',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='unit_price',
            new_name='unitPrice',
        ),
    ]
